swagger: "2.0"
info:
  version: "1.0.0"
  title: "Delibrary"
  description: "Delibrary is a place of interaction that encourages the exchange of books between users."
host: "localhost:2020"
basePath: "/v1"
tags:
- name: "user"
  description: "Everything about Delibrary users."
- name: "exchange"
  description: "Everything about the exchanges of books on Delibrary."
schemes:
- "https"
- "http"
paths:
  /utenti:
    get:
      tags:
      - "user"
      summary: "Get all Delibrary users."
      operationId: "getUsers"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Collection of all Delibrary users."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        default:
          description: "Unexpected error."
    post:
      tags:
      - "user"
      summary: "Add a new user to Delibrary."
      operationId: "addUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New user object."
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "User successfully added."
        "400":
          description: "Invalid user object."
        "403":
          description: "Username already in use."
        default:
          description: "Unexpected error."
  /utenti/{username}:
    get:
      tags:
      - "user"
      summary: "Get the user with the given username."
      operationId: "getUserByUsername"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "Username of the user to get."
        required: true
        type: "string"
      responses:
        "200":
          description: "User object with the given username."
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid username."
        "404":
          description: "No user found with the given username."
        default:
          description: "Unexpected error."
    put:
      tags:
      - "user"
      summary: "Update the user with the given username."
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "Username of the user to update."
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated version of the user object."
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "User successfully updated."
        "400":
          description: "Invalid username or user object."
        "401":
          description: "Not authenticated."
        "404":
          description: "No user found with the given username."
        default:
          description: "Unexpected error."
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs the user into the system."
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "Username for login."
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for login IN CLEAR TEXT."
        required: true
        type: "string"
        format: "password"
      responses:
        "200":
          description: "User logged in."
        "401":
          description: "Invalid username or password."
        default:
          description: "Unexpected error."
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session."
      description: "This can only be done by the logged in user."
      operationId: "logoutUser"
      produces:
      - "application/json"
      responses:
        "200":
          description: "User logged out."
        "401":
          description: "Not authenticated."
        default:
          description: "Unexpected error."
  /utenti/{username}/scambi:
    get:
      tags:
      - "exchange"
      summary: "Get all the exchanges in which the user with the given username is involved."
      operationId: "getUserExchanges"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "Username of the user whose exchanges are to be obtained."
        required: true
        type: "string"
      responses:
        "200":
          description: "Collection of exchange objects in which the user is involved."
          schema:
            type: array
            items:
              $ref: "#/definitions/Exchange"
        "400":
          description: "Invalid username."
        "404":
          description: "No user found with the given username."
        default:
          description: "Unexpected error."
  /scambi/{id}:
    get: 
      tags:
      - "exchange"
      summary: "Get the exchange with the given ID."
      operationId: "getExchange"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the exchange to get."
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Exchange object with the given ID."
          schema:
            $ref: "#/definitions/Exchange"
        "400": 
          description: "Invalid ID."
        "404":
          description: "No exchange found with the given ID."
        default:
          description: "Unexpected error."
    put:
      tags:
      - "exchange"
      summary: "Update the exchange with the given ID."
      description: "This can only be done by the logged in user."
      operationId: "updateExchange"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the exchange to update."
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Updated version of the exchange object."
        required: true
        schema:
          $ref: "#/definitions/Exchange"
      responses:
        "201":
          description: "Exchange successfully updated."
        "400":
          description: "Invalid ID or exchange object."
        "401":
          description: "Not authenticated."
        "404":
          description: "No exchange found with the given ID."
        default:
          description: "Unexpected error."
    delete:
      tags:
      - "exchange"
      summary: "Delete the exchange with the given ID."
      description: "This can only be done by the logged in user."
      operationId: "deleteExchange"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the exchange to delete."
        required: true
        type: "integer"
        format: "int64"
      responses:
        "201":
          description: "Exchange successfully deleted."
        "400":
          description: "Invalid ID."
        "401":
          description: "Not authenticated."
        "404":
          description: "No exchange found with the given ID."
        default:
          description: "Unexpected error."
definitions:
  User:
    type: "object"
    title: "User"
    properties:
      username:
        type: "string"
        example: "nicheosala"
      email:
        type: "string"
        format: "email"
        example: "example@domain.org"
      name:
        type: "string"
        example: "Nicolò"
      surname:
        type: "string"
        example: "Sala"
      library:
        type: "array"
        items:
          $ref: "#/definitions/BookOwnership"
      wishlist:
        type: "array"
        items:
          $ref: "#/definitions/BookWillingness"
  BookOwnership:
    type: "object"
    title: "Book in library"
    properties:
      ISBN:
        type: "string"
        pattern: "/(978)?[0-9]{10}/"
        example: "1280229045"
      owner:
        $ref: "#/definitions/User"
      position:
        $ref: "#/definitions/Position"
      status:
        type: "string"
        enum:
          - "have"
          - "am"
          - "will"
  BookWillingness:
    type: "object"
    title: "Book in wishlist"
    properties:
      ISBN:
        type: "string"
        pattern: "/(978)?[0-9]{10}/"
        example: "9780491212489"
      owner:
        $ref: "#/definitions/User"
  Position:
    type: "object"
    title: "Position"
    properties:
      region:
        type: "string"
        example: "Lombardia"
      province:
        type: "string"
        example: "Lecco"
      city:
        type: "string"
        example: "Brivio"
  Exchange:
    type: "object"
    title: "Exchange"
    properties:
      id:
        type: "integer"
        format: "int64"
      proposingUser:
        $ref: "#/definitions/User"
      respondingUser:
        $ref: "#/definitions/User"
      proposedBook:
        $ref: "#/definitions/BookOwnership"
      respondedBook:
        $ref: "#/definitions/BookOwnership"
      status:
        type: "string"
        enum:
        - "proposed"
        - "completed"